---
- hosts: localhost
  connection: local 
  tasks:
    - name: Log into DockerHub
      docker_login:
        registry: docker.io
        username: siddeshg672
        password: "{{ docker_password }}"
        
    - name: pull an image
      docker_image:
        name: "siddeshg672/devopsapp:test-deploy_{{ BUILD_NUMBER }}"
        source: pull

    - name: remove container
      docker_container:
        name: devopsAppDeploy
        state: absent
        
    - name: create a application container
      docker_container:
        name: devopsAppDeploy
        image: "siddeshg672/devopsapp:test-deploy_{{ BUILD_NUMBER }}"
        state: started
        exposed_ports:
          - 8111
